#!/bin/bash
# Dataset: ECG5000
# Method: pureinputaware
# Seq Len: 140, Variates: 1, Classes: 5


# ========== TRIGGER MODEL: citst ==========

# citst | opt=adam_sgd_best | cfg=balanced | warmup=0 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=adam_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=adam_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=adam_sgd_best | cfg=balanced | warmup=5 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=adam_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=adam_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_sgd_best | cfg=balanced | warmup=0 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_sgd_best | cfg=balanced | warmup=5 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_adam_best | cfg=balanced | warmup=0 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_adam_best | cfg=balanced | warmup=0 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_adam_best | cfg=balanced | warmup=0 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_adam_best | cfg=balanced | warmup=5 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_adam_best | cfg=balanced | warmup=5 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# citst | opt=sgd_adam_best | cfg=balanced | warmup=5 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel citst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0


# ========== TRIGGER MODEL: cpatchtst ==========

# cpatchtst | opt=adam_sgd_best | cfg=balanced | warmup=0 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=adam_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=adam_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=adam_sgd_best | cfg=balanced | warmup=5 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=adam_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=adam_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_sgd_best | cfg=balanced | warmup=0 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_sgd_best | cfg=balanced | warmup=5 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_adam_best | cfg=balanced | warmup=0 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_adam_best | cfg=balanced | warmup=0 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_adam_best | cfg=balanced | warmup=0 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_adam_best | cfg=balanced | warmup=5 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_adam_best | cfg=balanced | warmup=5 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# cpatchtst | opt=sgd_adam_best | cfg=balanced | warmup=5 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel cpatchtst --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0


# ========== TRIGGER MODEL: ctimesnet ==========

# ctimesnet | opt=adam_sgd_best | cfg=balanced | warmup=0 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=adam_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=adam_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=adam_sgd_best | cfg=balanced | warmup=5 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=adam_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=adam_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt adam --trigger_lr 0.001 --trigger_weight_decay 0.0 --surrogate_opt sgd --surrogate_lr 0.01 --surrogate_weight_decay 0.0005 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_sgd_best | cfg=balanced | warmup=0 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_sgd_best | cfg=balanced | warmup=0 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_sgd_best | cfg=balanced | warmup=5 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_sgd_best | cfg=balanced | warmup=5 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.05 --trigger_weight_decay 0.001 --surrogate_opt sgd --surrogate_lr 0.05 --surrogate_weight_decay 0.001 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_adam_best | cfg=balanced | warmup=0 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_adam_best | cfg=balanced | warmup=0 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_adam_best | cfg=balanced | warmup=0 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 0 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_adam_best | cfg=balanced | warmup=5 | grad_clip=no_clip | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 0.0 --surrogate_grad_clip 0.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_adam_best | cfg=balanced | warmup=5 | grad_clip=clip_5 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 5.0 --surrogate_grad_clip 5.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

# ctimesnet | opt=sgd_adam_best | cfg=balanced | warmup=5 | grad_clip=clip_10 | epochs=75 | poison=normal_10pct
python -u main.py --train_mode backdoor --method pureinputaware --Tmodel ctimesnet --bd_type all2all --root_path ./dataset/ECG5000 --seq_len 140 --trigger_epochs 75 --bd_train_epochs 40 --warmup_epochs 5 --target_label 0 --auto_bd_arch True --auto_batch_size True --patch_len 16 --stride 8 --trigger_opt sgd --trigger_lr 0.01 --trigger_weight_decay 0.0005 --surrogate_opt adam --surrogate_lr 0.001 --surrogate_weight_decay 0.0 --surrogate_L2_penalty 0.0 --trigger_grad_clip 10.0 --surrogate_grad_clip 10.0 --poisoning_ratio 0.1 --p_attack 0.5 --lambda_div 1.0 --lambda_cross 1.0

